version: '2'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: luontola/territory-bro-web
    environment:
      API_URL: http://api:8080
    mem_reservation: 10m
    mem_limit: 20m
    ports:
      - "127.0.0.1:8080:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: luontola/territory-bro-api
    environment:
      PUBLIC_URL: http://localhost:8080
      NREPL_PORT: 7000
      AUTH0_DOMAIN: luontola.eu.auth0.com
      AUTH0_CLIENT_ID: 8tVkdfnw8ynZ6rXNndD6eZ6ErsHdIgPi
      SUPER_USERS:
      SUPPORT_EMAIL: support@example.com
      DATABASE_URL: jdbc:postgresql://db:5432/territorybro?user=territorybro&password=territorybro
      GIS_DATABASE_HOST: localhost
    mem_reservation: 150m
    mem_limit: 200m
    ports:
      - "127.0.0.1:8081:8080"
      - "127.0.0.1:7000:7000"

  db:
    image: mdillon/postgis:11
    environment:
      POSTGRES_USER: territorybro
      POSTGRES_PASSWORD: territorybro
    mem_reservation: 30m
    mem_limit: 150m
    ports:
      - "127.0.0.1:5432:5432"

  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: secret
    mem_limit: 500m
    ports:
      - "127.0.0.1:8082:80"
