version: '2'
services:
  dev:
    image: luontola/territory-bro-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "5000:5000"
    volumes:
     - .:/project
     - $HOME/.m2/repository:/home/dev/.m2/repository
