version: '2'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: luontola/territory-bro-web
    environment:
      API_URL: http://api:8080
    mem_reservation: 10m
    mem_limit: 20m
    ports:
    - "8080:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: luontola/territory-bro-api
    environment:
      AUTH0_DOMAIN: luontola.eu.auth0.com
      AUTH0_CLIENT_ID: 8tVkdfnw8ynZ6rXNndD6eZ6ErsHdIgPi
      SUPER_ADMIN: google-oauth2|102883237794451111459
      DATABASE_URL: jdbc:postgresql://db:5432/territorybro?user=territorybro&password=territorybro
    mem_reservation: 150m
    mem_limit: 200m
    ports:
    - "8081:8080"

  db:
    image: mdillon/postgis:9.6
    environment:
      POSTGRES_USER: territorybro
      POSTGRES_PASSWORD: territorybro
    mem_reservation: 30m
    mem_limit: 150m
    ports:
    - "5432:5432"
