version: '2'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: luontola/territory-bro-web
    environment:
      API_URL: http://api:8080
    mem_reservation: 10m
    mem_limit: 20m
    ports:
    - "8080:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: luontola/territory-bro-api
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/territorybro?user=territorybro&password=territorybro
    mem_reservation: 150m
    mem_limit: 200m
    ports:
    - "8081:8080"

  db:
    image: mdillon/postgis:9.6
    environment:
      POSTGRES_USER: territorybro
      POSTGRES_PASSWORD: territorybro
    mem_reservation: 30m
    mem_limit: 150m
    ports:
    - "5432:5432"
