services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: luontola/territory-bro
    platform: linux/amd64
    environment:
      PUBLIC_URL: http://localhost:8080
      AUTH0_DOMAIN: luontola.eu.auth0.com
      AUTH0_CLIENT_ID: 8tVkdfnw8ynZ6rXNndD6eZ6ErsHdIgPi
      AUTH0_CLIENT_SECRET: nS2e4VPlaXyKuYwbsZ75NFXP6TMQ075HZ6cVu_bEasR8rXF8ggMrU5hCP3x7zmgE
      SUPER_USERS:
      SUPPORT_EMAIL: support@example.com
      DATABASE_URL: jdbc:postgresql://db:5432/territorybro?user=territorybro&password=territorybro
      GIS_DATABASE_HOST: localhost
    mem_reservation: 500m
    mem_limit: 500m
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:7000:7000"

  # TODO: official arm64 build of postgis - currently using test builds
  # https://github.com/postgis/docker-postgis/issues/216#issuecomment-2016916803
  # https://github.com/postgis/docker-postgis/pull/356
  # https://hub.docker.com/r/imresamu/postgis/tags
  db:
    #image: postgis/postgis:13-3.1
    image: imresamu/postgis:13-3.4
    environment:
      POSTGRES_USER: territorybro
      POSTGRES_PASSWORD: territorybro
    volumes:
      - postgres-storage:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    mem_reservation: 250m
    mem_limit: 500m
    ports:
      - "127.0.0.1:5432:5432"

  pgadmin:
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: secret
    mem_limit: 500m
    ports:
      - "127.0.0.1:8082:80"

volumes:
  postgres-storage:
