version: '2'
services:
  dev:
    image: luontola/territory-bro-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "8080:8080"
    volumes:
     - .:/project
     - $HOME/.m2/repository:/home/dev/.m2/repository
     - $HOME/.lein/self-installs:/home/dev/.lein/self-installs
