# Site settings
title: Territory Bro
tagline: Territory card management made easy
description: Tool for managing territory cards in the congregations of Jehovah's Witnesses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://territorybro.com" # the base hostname & protocol for your site

navigation:
  - title: 👋 Introduction
    url: /
  - title: 🚀 Get Started
    url: /guide/#getting-started
  - title: 📒 User Guide
    url: /guide/
  - title: 👤 Login
    url: https://beta.territorybro.com
  - title: 📰 News
    url: https://groups.google.com/forum/#!forum/territory-bro-announcements
  - title: 🧬 Source Code
    url: https://github.com/luontola/territory-bro

# Build settings
markdown: kramdown
